quarkus:
  http:
    auth:
      permission:
        open:
          paths: /health/ingest
          policy: permit
        # Prevent access for unauthenticated
        secured:
          paths: /*
          policy: authenticated

  google:
    cloud:
      project-id: cinnes-dev

      firebase:
        auth:
          enabled: true

'%dev':
  health:
    ingest:
      key: test