quarkus:
  http:
    auth:
      permission:
        secured:
          paths: /*
          policy: authenticated

  google:
    cloud:
      project-id: cinnes-dev

      firebase:
        auth:
          enabled: true
