quarkus:
  http:
    auth:
      permission:
        open:
          paths: /health/ingest
          policy: permit
        # Prevent access for unauthenticated
        secured:
          paths: /*
          policy: authenticated

  google:
    cloud:
      project-id: cinnes-dev

      firebase:
        auth:
          enabled: true

  log:
    sentry:
      in-app-packages: dev.cinnes
      dsn: https://3e96aee38169343492bf1be4663b6cf3@o4507648641204224.ingest.de.sentry.io/4507648652804176

'%dev':
  health:
    ingest:
      key: test